### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Client'

### ISSUE THREAD

**Issue by sachinprabhu007** [harinij/100DaysOfCode#3]
It results in following error when i run gamebot basic version. 
Thanks ! 

> [2018-08-07 13:04:18,882] Making new env: flashgames.NeonRace-v0
> [2018-08-07 13:04:18,886] Writing logs to file: /tmp/universe-25716.log
> Traceback (most recent call last):
>   File "game_bot.py", line 4, in <module>
>     env.configure(remotes=1) # automatically creates a local docker container
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/gym/core.py", line 224, in configure
>     self._configure(*args, **kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/universe/vectorized/core.py", line 39, in _configure
>     super(Wrapper, self)._configure(**kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/gym/core.py", line 349, in _configure
>     return self.env.configure(*args, **kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/gym/core.py", line 224, in configure
>     self._configure(*args, **kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/universe/wrappers/render.py", line 18, in _configure
>     super(Render, self)._configure(**kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/universe/vectorized/core.py", line 39, in _configure
>     super(Wrapper, self)._configure(**kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/gym/core.py", line 349, in _configure
>     return self.env.configure(*args, **kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/gym/core.py", line 224, in configure
>     self._configure(*args, **kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/universe/wrappers/throttle.py", line 27, in _configure
>     super(Throttle, self)._configure(**kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/universe/vectorized/core.py", line 39, in _configure
>     super(Wrapper, self)._configure(**kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/gym/core.py", line 349, in _configure
>     return self.env.configure(*args, **kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/gym/core.py", line 224, in configure
>     self._configure(*args, **kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/universe/envs/vnc_env.py", line 199, in _configure
>     use_recorder_ports=record,
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/universe/remotes/build.py", line 19, in build
>     n=n,
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/universe/remotes/docker_remote.py", line 44, in __init__
>     self._assigner = PortAssigner(reuse=reuse)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/universe/remotes/docker_remote.py", line 162, in __init__
>     self.client, self.info = get_client()
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/universe/remotes/docker_remote.py", line 156, in get_client
>     return docker.Client(base_url=host, version=client_api_version), info
> AttributeError: 'module' object has no attribute 'Client'
>

**Comment by harinij** [comment]
Looks like your installation is missing the module. Verify the steps in init if all of them are added.
